# Generated by Django 3.1.3 on 2021-03-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0003_vuelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vuelo',
        ),
    ]
